#region Copyright Syncfusion Inc. 2001-2017.
// Copyright Syncfusion Inc. 2001-2017. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SampleBrowser.iOS
{
	public partial class DynamicLaunchScreenViewController : UIViewController
	{
		public DynamicLaunchScreenViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
